[package]
name = "template_build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
include_dir = "0.7.3"
regex = "1.8.1"
zip-extract = "0.1.2"
